controller_manager:
  ros__parameters:
    update_rate: 10 #How often diffbot_base_controller gets updated 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_motor_joint"]
    right_wheel_names: ["right_motor_joint"]

    wheel_separation: 0.31
    wheel_radius: 0.035

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0 
    right_wheel_radius_multiplier: 1.0 #If the robot veers left, increase right_wheel_radius_multiplier to compensate 

    publish_rate: 50.0 #How often /diffbot_base_controller/odom and /tf messages are published
    odom_frame_id: odom
    base_frame_id: base_link

    #CHECK THESE ODOM COVARIANCE VALUES
    pose_covariance_diagonal : [0.05, 999.0, 999.0, 999.0, 999.0, 0.1] # x y z roll pitch yaw
    twist_covariance_diagonal: [0.05, 999.0, 999.0, 999.0, 999.0, 0.1]
    
    # pose_covariance_diagonal : [0.01, 999.0, 999.0, 999.0, 999.0, 999.0] # x y z roll pitch yaw
    # twist_covariance_diagonal: [0.01, 999.0, 999.0, 999.0, 999.0, 999.0]

    open_loop: false 
    enable_odom_tf: true #I WANT EKF TO PUBLISH TF NOT THIS

    cmd_vel_timeout: 0.5 #if no cmd_vel is received for 0.5 seconds, robot'll stop
    emergency_stop_enabled: true
    max_cmd_vel_age: 0.5 
    use_stamped_vel: false
    #publish_limited_velocity: true 
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

joint_state_broadcaster:
  ros__parameters: {}
