ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    use_control_input: false
    publish_tf: true #ISKO TF PUBLISH KARNA CHAIYE
    # imu0_angular_velocity_covariance: 10
    # imu0_orientation_covariance: 5

    # Wheel odometry from diff drive controller




    odom0: /diffbot_base_controller/odom
    odom0_differential: true
    odom0_config: [true, true, false,    # x, y, z position
                   false, false, true,   # roll, pitch, yaw
                   true, true, false,    # x, y, z velocity
                   false, false, true,   # roll, pitch, yaw velocity
                   false, false, false]  # x, y, z acceleration is usually not measured well from odom
    
    

    #CHECK - COMMENT OUT THESE IF NECESSARY 
    # odom0_pose_rejection_threshold: 5.0     # meters
    # odom0_twist_rejection_threshold: 2.0    # rad/s If difference between incoming pose/twist and EKF's current estimate > this, it doesn't fuse it.
    # odom0_queue_size: 10.0 # how many messages to buffer before fusing

    

    #IMU data

    imu0: /demo/imu
    imu0_differential: false
    imu0_config: [false, false, false,   # position
                  false, false, true,    # orientation (only yaw)
                  false, false, false,   # linear velocity
                  false, false, true,    # angular velocity (only yaw)
                  false, false, false]   # linear acceleration

    imu0_orientation_covariance: [999.0, 0.0, 0.0,
                              0.0, 999.0, 0.0,
                              0.0, 0.0, 0.01]  # Only yaw

    imu0_angular_velocity_covariance: [999.0, 0.0, 0.0,
                                   0.0, 999.0, 0.0,
                                   0.0, 0.0, 0.02]  # Only yaw rate


    # Frame configuration
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom