ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true #ISKO TF PUBLISH KARNA CHAIYE
    # Wheel odometry from diff drive controller
    odom0: /diffbot_base_controller/odom
    odom0_config: [true, true, false,    # x, y, z position
                   false, false, true,   # roll, pitch, yaw
                   true, true, false,    # x, y, z velocity
                   false, false, true,   # roll, pitch, yaw velocity
                   false, false, false]  # x, y, z acceleration
    # IMU data
    

    imu0: /demo/imu
    imu0_config: [false, false, false,   # position
                  false, false, true,    # orientation (only yaw)
                  false, false, false,   # linear velocity
                  false, false, true,    # angular velocity (only yaw)
                  false, false, false]   # linear acceleration


    # Frame configuration
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom


    #Ok so basically there's some issue in the chain map->odom->base_link
    #It's certain that map->odom is being published by SLAM toolbox only because when that node is ended, that transform dies
    #However, on running the ekf node along with SLAM node, the robot is jittering. 