slam_toolbox:
  ros__parameters:
    publish_tf_map: true
    use_odometry: true
    odom_topic: /odometry/filtered
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_sim_time: false
    minimum_laser_range: 0.15
    maximum_laser_range: 12.0
    resolution: 0.05